CREATE TABLE IF NOT EXISTS digital_galleries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  `year_month` VARCHAR(7) NOT NULL UNIQUE,
  display_name VARCHAR(50) NOT NULL,
  cover_photo_id INT NULL,
  created_by INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
